import fs from "node:fs/promises";
import path from "node:path";
import PDFDocument from "pdfkit";
import { NextRequest, NextResponse } from "next/server";
import { and, asc, eq } from "drizzle-orm";
import { getSessionUser } from "@/lib/auth/session";
import { getDb } from "@/lib/db/client";
import { loanRepayments, loans, profiles } from "@/lib/db/schema";
import { enforceRouteRateLimit } from "@/lib/rate-limit";

export const runtime = "nodejs";

type RouteContext = {
  params: Promise<{ id: string }>;
};

type LoanRepaymentRow = {
  id: string;
  amount: number | string | null;
  created_at: string | null;
};

function formatDate(value: string | null) {
  if (!value) {
    return "-";
  }

  return new Date(value).toLocaleString("en-US", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatXlm(value: number | string | null | undefined) {
  return `${Number(value ?? 0).toFixed(2)} XLM`;
}

async function generateReceiptPdf({
  loanId,
  borrowerId,
  borrowerName,
  principalAmount,
  aprBps,
  durationDays,
  repaidAmount,
  createdAt,
  finalRepaymentAt,
  repayments,
}: {
  loanId: string;
  borrowerId: string;
  borrowerName: string;
  principalAmount: number | string | null;
  aprBps: number | string | null;
  durationDays: number | string | null;
  repaidAmount: number | string | null;
  createdAt: string | null;
  finalRepaymentAt: string | null;
  repayments: LoanRepaymentRow[];
}) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];

  const pdfBufferPromise = new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  try {
    const logoPath = path.join(process.cwd(), "public", "logo.png");
    const logo = await fs.readFile(logoPath);
    doc.image(logo, 50, 42, { width: 68 });
  } catch {
    // Logo is optional for receipt generation.
  }

  doc
    .fillColor("#3f2a69")
    .fontSize(22)
    .text("TrustLend Loan Receipt", 135, 50)
    .fillColor("#6b7280")
    .fontSize(10)
    .text("Proof of loan repayment for external credit verification", 135, 78);

  doc
    .moveTo(50, 112)
    .lineTo(545, 112)
    .strokeColor("#e5e7eb")
    .stroke();

  doc.fillColor("#111827").fontSize(12);

  const summaryRows = [
    ["Receipt generated", formatDate(new Date().toISOString())],
    ["Borrower name", borrowerName],
    ["Borrower ID", borrowerId],
    ["Loan ID", loanId],
    ["Original loan amount", formatXlm(principalAmount)],
    ["Total repaid", formatXlm(repaidAmount)],
    ["APR", `${(Number(aprBps ?? 0) / 100).toFixed(2)}%`],
    ["Loan term", `${Number(durationDays ?? 0)} days`],
    ["Loan created", formatDate(createdAt)],
    ["Final repayment", formatDate(finalRepaymentAt)],
  ];

  let y = 130;
  for (const [label, value] of summaryRows) {
    doc
      .fillColor("#6b7280")
      .fontSize(10)
      .text(label, 50, y, { width: 160 })
      .fillColor("#111827")
      .fontSize(11)
      .text(value, 220, y, { width: 290 });
    y += 22;
  }

  y += 10;
  doc
    .fillColor("#3f2a69")
    .fontSize(14)
    .text("Repayment History", 50, y);

  y += 26;
  doc
    .fillColor("#6b7280")
    .fontSize(10)
    .text("Repayment ID", 50, y, { width: 170 })
    .text("Timestamp", 230, y, { width: 180 })
    .text("Amount", 430, y, { width: 100, align: "right" });

  y += 14;
  doc
    .moveTo(50, y)
    .lineTo(545, y)
    .strokeColor("#d1d5db")
    .stroke();

  y += 10;
  repayments.forEach((repayment) => {
    if (y > 730) {
      doc.addPage();
      y = 60;
    }

    doc
      .fillColor("#111827")
      .fontSize(10)
      .text(String(repayment.id).slice(0, 16), 50, y, { width: 170 })
      .text(formatDate(repayment.created_at), 230, y, { width: 180 })
      .text(formatXlm(repayment.amount), 430, y, { width: 100, align: "right" });
    y += 22;
  });

  doc
    .fillColor("#6b7280")
    .fontSize(9)
    .text(
      "This receipt was generated by TrustLend from its repayment records and verified borrower loan history.",
      50,
      760,
      { width: 495, align: "center" }
    );

  doc.end();
  return pdfBufferPromise;
}

export async function GET(request: NextRequest, context: RouteContext) {
  try {
    const rateLimited = await enforceRouteRateLimit(request);
    if (rateLimited) return rateLimited;

    const { id } = await context.params;
    const db = getDb();
    if (!db) {
      return NextResponse.json({ error: "Database unavailable" }, { status: 503 });
    }

    const user = await getSessionUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const [[loan], repaymentRows, [profile]] = await Promise.all([
      db
        .select({
          id: loans.id,
          borrowerId: loans.borrowerId,
          principalAmount: loans.principalAmount,
          repaidAmount: loans.repaidAmount,
          aprBps: loans.aprBps,
          durationDays: loans.durationDays,
          status: loans.status,
          createdAt: loans.createdAt,
        })
        .from(loans)
        .where(and(eq(loans.id, id), eq(loans.borrowerId, user.id)))
        .limit(1),
      db
        .select({ id: loanRepayments.id, amount: loanRepayments.amount, createdAt: loanRepayments.createdAt })
        .from(loanRepayments)
        .where(eq(loanRepayments.loanId, id))
        .orderBy(asc(loanRepayments.createdAt)),
      db.select({ fullName: profiles.fullName }).from(profiles).where(eq(profiles.id, user.id)).limit(1),
    ]);

    if (!loan) {
      return NextResponse.json({ error: "Loan not found" }, { status: 404 });
    }

    if (loan.status !== "repaid") {
      return NextResponse.json({ error: "Receipt is only available for repaid loans" }, { status: 400 });
    }

    const repayments: LoanRepaymentRow[] = repaymentRows.map((r) => ({
      id: r.id,
      amount: r.amount,
      created_at: r.createdAt.toISOString(),
    }));
    const finalRepaymentAt = repayments.at(-1)?.created_at ?? null;

    const pdf = await generateReceiptPdf({
      loanId: loan.id,
      borrowerId: loan.borrowerId,
      borrowerName: profile?.fullName || user.fullName || "TrustLend Borrower",
      principalAmount: loan.principalAmount,
      aprBps: loan.aprBps,
      durationDays: loan.durationDays,
      repaidAmount: loan.repaidAmount,
      createdAt: loan.createdAt.toISOString(),
      finalRepaymentAt,
      repayments,
    });

    return new NextResponse(new Uint8Array(pdf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="trustlend-loan-receipt-${id}.pdf"`,
        "Cache-Control": "private, no-store, max-age=0",
      },
    });
  } catch (error) {
    console.error("Loan receipt generation error:", error);
    return NextResponse.json({ error: "Failed to generate receipt" }, { status: 500 });
  }
}
